"""create_users_tables

Revision ID: 83bc96a9f2af
Revises: 
Create Date: 2026-06-03 15:48:57.898115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bc96a9f2af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('preferred_categories', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_location', sa.String(length=100), nullable=True),
    sa.Column('ai_pref_vector', sa.JSON(), nullable=True),
    sa.Column('last_search_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('production_description', sa.Text(), nullable=True),
    sa.Column('avg_response_hrs', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_kg_sold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_no', sa.String(length=20), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('seller_profiles')
    op.drop_table('buyer_profiles')
    # ### end Alembic commands ###
