"""update user models

Revision ID: 9bd77e0cd748
Revises: 001efb8593ff
Create Date: 2026-06-18 16:35:23.092909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd77e0cd748'
down_revision: Union[str, Sequence[str], None] = '001efb8593ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer_profiles', sa.Column('profile_status', sa.String(length=30), nullable=False))
    op.add_column('seller_profiles', sa.Column('profile_status', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('active_role', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('registered_roles', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('users', 'registered_roles')
    op.drop_column('users', 'active_role')
    op.drop_column('seller_profiles', 'profile_status')
    op.drop_column('buyer_profiles', 'profile_status')
    # ### end Alembic commands ###
